### ISSUE TITLE
can't change pin/password ! help please

### ISSUE THREAD

**Issue by baadillahnabil** [ayavilevich/arduino-ble-ident-n-set#1]
this is what i got after uploading your sketch :

`Arduino BLE module identification and setup sketch.
Interact with this interface using serial in CR&LF mode.
Enter the number of the RX pin on the Arduino, TX on the module [8] :
Enter the number of the TX pin on the Arduino, RX on the module [9] :
Enter the number of the State pin on the Arduino, State on the module (enter -1 if not present or not connected) [7] :
Opening serial connection to BLE module at pins: 2, 3, -1
For this sketch, make sure the module is not connected to another BLE device.
This will make sure the device is in command mode.
A led on the module should be off or blinking.
Detecting module type
MLT-BT05 detected!
Sending command: AT+HELP
*******************************************************************
* Command             Description			           
*----------------------------------------------------------------
* AT                  Check if the command terminal work normally 
* AT+DEFAULT          Restore factory default			   

` 

could you please help me ? is it something wrong ??

**Comment by ayavilevich** [comment]
Hi, your output seems to cut at "Restore factory default". Is this where it ends when you are running the script or was it truncated at post time?

Regardless, I tried the pin change flow here with a MLT-BT-5 and the script fails because it tries to use a "PASS" command where the BLT uses "PIN", will issue a fix later. Can you try it manually and LMK if this resolves your issue?

Thanks for reporting.

**Comment by baadillahnabil** [comment]
@ayavilevich thanks before man, but i know what causing the problem, my MLT-BT05 only accept 6 digit PIN or passkey, that was making me confused because i want to change it to 9 digits and it keeps respon `ERR` . now i know why :) 

anyway thanks again for your sketch, it really help me a lot :)
